---
# Software installation  playbook

- name: Software Installation  as required
  hosts: all
  become: yes

  tasks:
  # First task
   - yum:
      name: "{{packages}}"
      state: present
    vars:
     packages:
      - httpd
      - git
      - tcpdump
      - php
  # Second task
   - service:
      name: httpd
      state: started
      enabled: yes

# Run the playbook
ansible-playbook softeware_installation.yml